name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extract-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.extract.outputs.targets }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract targets as JSON array
        id: extract
        uses: dcarbone/install-jq-action@v2
      - name: Get targets from bake file
        id: get-targets
        run: |
          TARGETS=$(docker buildx bake --file docker-bake.hcl --print | jq -c '[.target | keys[] | select(. != "default")]')
          echo "targets=$TARGETS" | tee -a ${GITHUB_OUTPUT}

  build:
    needs: extract-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.extract-targets.outputs.targets) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Check formatting
        run: make install-deps && make lint

      - name: Login container registries
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Check buildx bake
        run: docker buildx bake --file docker-bake.hcl --print

      - name: Build image for tag ${{ matrix.target }}
        if: github.ref == 'refs/heads/master'
        run: docker buildx bake --file docker-bake.hcl ${{ matrix.target }} --load

      - name: Publish image for tag ${{ matrix.target }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: docker buildx bake --file docker-bake.hcl ${{ matrix.target }} --push

      - name: Remove builder instances
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: docker buildx rm --all-inactive --force
