name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        target: [ "all", "20", "20-alpine", "19", "19-alpine", "18", "18-alpine", "17", "17-alpine", "16", "16-alpine", "15", "14", "13", "12", "11", "10", "9", "8", "7"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Check formatting
        run: make install-deps && make lint

      - name: Login container registries
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Check buildx bake
        run: docker buildx bake --file docker-bake.hcl --print

      - name: Build image for tag ${{ matrix.target }}
        run: docker buildx bake --file docker-bake.hcl ${{ matrix.target }}

      - name: Publish image for tag ${{ matrix.target }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: docker buildx bake --file docker-bake.hcl ${{ matrix.target }} --push

      - name: Remove builder instances
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: docker buildx rm --all-inactive --force
